# Generated by Django 2.2.6 on 2019-11-02 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 2, 8, 45, 12, 202072, tzinfo=utc)),
        ),
    ]
